XHTMLElement extend [
    
    anchor [
	<category: 'deprecated'>
	^self a
    ]

    break [
	<category: 'deprecated'>
	^self br
    ]

    definition [
	<category: 'deprecated'>
	^self dfn
    ]

    definitionData [
	<category: 'deprecated'>
	^self dd
    ]

    definitionList [
	<category: 'deprecated'>
	^self dl
    ]

    definitionTerm [
	<category: 'deprecated'>
	^self dt
    ]

    direction [
	<category: 'deprecated'>
	^self bdo
    ]

    emphasis [
	<category: 'deprecated'>
	^self em
    ]

    emphasis: aString [
	<category: 'deprecated'>
	^self em: aString
    ]

    fileInput [
	<category: 'deprecated'>
	^self file
    ]

    header [
	<category: 'deprecated'>
	^self h
    ]

    horizontalRule [
	<category: 'deprecated'>
	^self hr
    ]

    image [
	<category: 'deprecated'>
	^self img
    ]

    image: aString [
	<category: 'deprecated'>
	^self img: aString
    ]

    italic [
	<category: 'deprecated'>
	^self i
    ]

    italic: aString [
	<category: 'deprecated'>
	^self i: aString
    ]

    listItem [
	<category: 'deprecated'>
	^self li
    ]

    optionGroup [
	<category: 'deprecated'>
	^self optgroup
    ]

    orderedList [
	<category: 'deprecated'>
	^self ol
    ]

    paragraph [
	<category: 'deprecated'>
	^self p
    ]

    parameter [
	<category: 'deprecated'>
	^self param
    ]

    passwordInput [
	<category: 'deprecated'>
	^self password
    ]

    preformatted [
	<category: 'deprecated'>
	^self pre
    ]

    preformatted: aString [
	<category: 'deprecated'>
	^self pre: aString
    ]

    radioButton [
	<category: 'deprecated'>
	^self radio
    ]

    resetInput [
	<category: 'deprecated'>
	^self reset
    ]

    stylesheet [
	<category: 'deprecated'>
	^self css
    ]

    submitInput [
	<category: 'deprecated'>
	^self submit
    ]

    tableBody [
	<category: 'deprecated'>
	^self tbody
    ]

    tableData [
	<category: 'deprecated'>
	^self td
    ]

    tableFoot [
	<category: 'deprecated'>
	^self tfoot
    ]

    tableHead [
	<category: 'deprecated'>
	^self thead
    ]

    tableHeader [
	<category: 'deprecated'>
	^self th
    ]

    tableRow [
	<category: 'deprecated'>
	^self tr
    ]

    teletype [
	<category: 'deprecated'>
	^self tt
    ]

    textArea [
	<category: 'deprecated'>
	^self textarea
    ]

    unorderedList [
	<category: 'deprecated'>
	^self ul
    ]

    variable [
	<category: 'deprecated'>
	^self var
    ]

    var: aString [
	<category: 'deprecated'>
	^self var: aString
    ]
]
